Delete 1.13.0 from CI
For some reasons old rustc 1.18.0 and older started failing to parse the
registry overnight.

    error: An unknown error occurred

    Caused by:
      Feature `pretty` depends on `syntex_syntax` which is not an optional dependency.
    Consider adding `optional = true` to the dependency